#!/usr/bin/env bash
# getting Apache to run on the container.

docker run -p 8080:80 -d -it holbertonschool/265-0

docker exec -it $(docker ps -qf "ancestor=holbertonschool/265-0") /bin/bash

apt-get update

apt-get install apache2 -y

echo "Hello Holberton" > /var/www/html/index.html

exit

curl 0:8080

docker stop $(docker ps -qf "ancestor=holbertonschool/265-0")
docker rm $(docker ps -aqf "ancestor=holbertonschool/265-0")
sudo service apache2 restart